version: '3'
dotenv: [".env"]

vars:
  CERTS_DIR: "certs"
  ZITADEL_PRIVATE_KEY: "certs/331462024888320002.json"
  ZITADEL_DOMAIN: "http://localhost:8080"
  
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Generate all certificates for webhook server
  generate-webhook-certs:
    desc: Generate all certificates for webhook server
    cmds:
      - mkdir -p "{{.CERTS_DIR}}" && openssl req -x509 -nodes -newkey rsa:4096 -keyout "{{.CERTS_DIR}}/server.key" -out "{{.CERTS_DIR}}/server.crt" -days 1024 -subj "/CN=webhook.zitadel.svc" -sha256

  run-manager:
    desc: Run the email-provider-loops manager
    cmds:
      - |
          go run cmd/main.go manager \
          --newsletter-contact-group-name newsletter \
          --newsletter-contact-group-namespace default \
          --health-probe-bind-address :8082
    
    env:
      LOOPS_API_KEY: "{{.LOOPS_API_KEY}}"
      LOOPS_SIGNING_SECRET: "{{.LOOPS_SIGNING_SECRET}}"

  run-webhook:
    desc: Run the webhook server locally
    deps:
      - generate-webhook-certs
    cmds:
      - |
        go run ./cmd webhook \
          --webhook-port 8443 \
          --cert-dir "{{.CERTS_DIR}}" \
          --cert-file "server.crt" \
          --key-file "server.key" \
          --metrics-bind-address :8082 
